### ISSUE TITLE
Error: [rast] cannot open this file as a SpatRaster

### ISSUE THREAD

**Issue by millie-robson** [RangeShifter/RangeshiftR-tutorials#38]
Hello,

I am trying to run a patch-based model using the RangeShifter platform in RStudio, but I am encountering a few errors when trying to load in my habitat patches. 

The habitat patches were created in ArcMap and converted into raster format, then the attributes were exported as an asc. file. I am trying to run the following code to read in the habitat patches:

patches <- terra::rast(paste0(dirpath,'Inputs/Raster_MCE_Std2_10_largest_areas.asc'))

But I receive the following errors:
Error: [rast] cannot open this file as a SpatRaster: /Users/millierobson/Documents/UNI/MRes/RangeShifter/RangeShifter PM/Models/PM_Reintroduction/Inputs/Raster_MCE_Std2_10_largest_areas.asc
In addition: Warning message:
`/Users/millierobson/Documents/UNI/MRes/RangeShifter/RangeShifter PM/Models/PM_Reintroduction/Inputs/Raster_MCE_Std2_10_largest_areas.asc' not recognized as a supported file format. (GDAL error 4) 

I have installed and loaded all the relevant packages (raster, terra, rgdal).

I do not understand the errors here and I was hoping someone may be able to help. I have attached the asc. file. I appreciate any help!

Many thanks.

**Comment by JetteReeg** [comment]
Hi, 
unfortunately this is an issue related to the R package terra and not to RangeShiftR. 

I would recommend that you have a look at the issues discussed in the terra git repository or post your question there: https://github.com/rspatial/terra/issues/ 

I will close this issue but there is also an open discussion here regarding this problem: #39
