### ISSUE TITLE
Error: Found patch NA in valid habitat cell

### ISSUE THREAD

**Issue by millie-robson** [RangeShifter/RangeshiftR-tutorials#41]
Hello, I am currently trying to run a model to simulate the reintroduction of a species to an area following this tutorial: https://damariszurell.github.io/EEC-QCB/RS2_lynx.html

I have a map of suitable habitat patches and a land cover map for the area. When I try to run the code I receive an error when I run the simulation. The error says: Found patch NA in valid habitat cell. Error reading landscape 0 - aborting

Has anyone encountered this error before? Would anyone be able to help me fix this? I have attached both the patch file and the landscape file, though the cell size, resolution and extent of both files match and the headers seem to be ok.

Many thanks!
[lcm_100m.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/12228728/lcm_100m.txt)
[mce1_5sites_new.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/12228730/mce1_5sites_new.txt)

**Comment by millie-robson** [comment]
Hi,

Thank you for the response. I understand the error message but I am not sure how to fix the problem. My patch map has 5 patches of different sizes, I have just made a new patch file with the same 5 patches but also a patch representing the rest of the study area with a value of 0. I now have a new error that says: Found invalid habitat code.

These errors may seem obvious to you but I have followed the tutorial and all the steps correctly so it is not obvious to me and I am really struggling to understand why it is going wrong at this point. 

I have attached the new patch file I have been using, anything to help me understand where I am going wrong would be much appreciated.
[mce1_5sites_new1.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/12230420/mce1_5sites_new1.txt)


Many thanks

**Comment by annekathleenmalchow** [comment]
The patch ID zero is reserved for the matrix patch which includes all non-habitat cells (those that contain a habitat value of zero). Habitat patches must have IDs that are consecutive integers starting from one, i.e. 1, 2,3, ... . Therefore, you should give your new patch the ID six.

**Comment by millie-robson** [comment]
Apologies, I am still not clear on this. For my patch file, I have a patch with an ID of 0. This represents the matrix patch, while patches 1-5 are the 5 suitable breeding patches that individuals could be reintroduced to. I assumed the patch with an ID of 0 represents an area that is not suitable for breeding but that individuals could still disperse through. I have tried to format my patch map so that it matches that of the tutorial, where there is a patch ID 0 and then IDs starting from 1. If I gave the new patch an ID of six would it then assume that the patch was a suitable breeding patch?

**Comment by annekathleenmalchow** [comment]
RS checks the habitat and patch maps for a few assumptions that it makes. Specifically, the habitat and patch maps should have NAs in matching cells. For all non-NA cells, those cells with habitat = 0 (i.e. matrix cells) should also have the patch ID = 0. Further, cells with habitat > 0 should have patch IDs 1, 2,3, ... . If any of these requirements are not met, RS throws an error. Are these requirements all given for your pair of habitat and patch maps?

**Comment by millie-robson** [comment]
Ok, I am really sorry I am still not sure what you mean. So, I have my patch map with patch 0 that is not suitable for breeding, and then I have patched 1-5 that are suitable for breeding. My landscape file is just a land cover map for the study area (there are 21 land cover categories i.e., the different habitat classes used to set the per-step mortality in the dispersal module). From my understanding to model reintroductions you would set up a text file where a number of individuals are introduced per patch and RS simulates range expansion from the patches based on the per-step mortality and movement costs defined for the landscape file. Is that correct?

**Comment by annekathleenmalchow** [comment]
The patch map does not define what is habitat and what is matrix (or, suitable / unsuitable, respectively), this is defined in the habitat map. But if a patch map is given, RS requires that all cells that are defined unsuitable should get the patch ID zero. For habitat classes, it depends on the value of `K_or_DensDep` in the landscape module which habitat classes are habitat or matrix. All habitat classes with a carrying capacity / denisty dependence strength of zero are understood to be matrix.

**Comment by millie-robson** [comment]
Ok, so if on my patch map there is a patch with an ID zero that has how ever many cells, but these cells do not match the cells of the habitat classes that have a value of zero it will not work?

Apologies for the many questions, I am finding it hard to get my head around - thank you for your help.

**Comment by annekathleenmalchow** [comment]
Well, this is the case with habitat suitability maps. With habitat classes its one more step to think because they code for different values of habitat suitability. So patch ID should be zero in all matrix cells, which are all cells that have a habitat class that is assigned a zero in `K_or_DensDep`.

**Comment by millie-robson** [comment]
Ok, I understand what you are saying. At the moment my patch map only has 5 patches, these were isolated from a map that had lots of patches but the 5 selected patches are the ones large enough for a potential reintroduction. In RS should I be using a patch map with all patches and only run the simulations on the selected patches that are large enough. Since the patch map is largely based on woodland areas, this way would it match up better with the land cover map? I hope that make sense

**Comment by annekathleenmalchow** [comment]
This doesn't relate to the original question anymore, which was about the error message stated above. Were you able to resolve this issue with the answers given?

If you have other questions, please open a new thread for this. Also please note that **Issues** on GitHub are meant to report bugs or other code-related problems. If you have thematic questions, please post them in the **Discussions** forum.

**Comment by ee20gr** [comment]
Hi, I am experiencing the same issue and getting the error: "Found patch NA in valid habitat cell. Error reading landscape 0 - aborting". I understand from the above thread why I am getting this error, but am unsure how to identify where these error cells are in my files or how to fix the issue? Any suggestions would be appreciated! I have included the three maps I am using, with HabitatMap being the habitat map, PatchesMap being the patch map, and InitialPatchMap being the initial species distribution map. 
[HabitatMap.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/14366151/HabitatMap.txt)
[InitialPatchMap.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/14366152/InitialPatchMap.txt)
[PatchesMap.txt](https://github.com/RangeShifter/RangeshiftR-tutorials/files/14366153/PatchesMap.txt)

**Comment by JetteReeg** [comment]
Hi, 

please note that the issues section here is meant to report technical problems regarding the RangeShiftR tutorials. Please use the [discussion forum](https://github.com/RangeShifter/RangeshiftR-tutorials/discussions) to post questions regarding technical problems using/applying the RangeShiftR package. Additionally, please be aware, that question on how to prepare and handle raster files would be better suited in raster related forums (e.g. [the terra repository](https://github.com/rspatial/terra/issues)).

To answer your question: The error message tells you that there are cell which belong to habitat (so not-NA cells in the habitat map), but have NA values in the patch map. I recommend, to merge both files (as XYZ data.frames) and check those cells, which have a value in the habitat map, but NA in the patch map:
```
library(terra)
# load data
habitat <- rast("HabitatMap.txt")
patches <- rast("PatchesMap.txt")
# convert to XYZ data.frame
habitat.xyz <- as.data.frame(habitat, xy=T)
patches.xyz <- as.data.frame(patches, xy=T)
# merge with habitat map being the basis
habitat.patches <- merge(habitat.xyz, patches.xyz, all.x=T)
# show cells with habitat value, but patch NAs
habitat.patches[habitat.patches$HabitatMap>=0 & is.na(habitat.patches$PatchesMap),]
```
Best,
Jette
